Add initial project structure;
Vocovo/Edge-devices-manager pull request #1
Opened 2023-07-26 11:30 UTC by vlad-dubrovski

Card: https://vocovo.atlassian.net/jira/software/c/projects/VOC/boards/55?modal=detail&selectedIssue=VOC-3242
Add initial project structure;
Add docker test;

2023-07-26 12:43 UTC, iryna-markovich-vocovo commented on docker-compose.yml
> +      - devices-manager-network
should not it be `devices-network` to be common network for devices service and reg module?

2023-07-26 12:49 UTC, iryna-markovich-vocovo commented on src/index.ts
> +main()
add please empty lines at the end of each file (where it is required)

2023-07-26 12:49 UTC, iryna-markovich-vocovo requested changes

2023-07-26 12:49 UTC, iryna-markovich-vocovo commented on src/index.ts
> +main()
add please empty lines at the end of each file (where it is required)

2023-07-26 12:56 UTC, iryna-markovich-vocovo commented
just out of interest do we ok with a name of the repo starts with a capital letter - `Edge-devices-manager`?

2023-07-26 13:08 UTC, iryna-markovich-vocovo commented on acceptance-test/docker.test.ts
> +const dockerTag = argv.filter((x) => x.startsWith('--containerTag='))[0]?.split('=')[1]
dockerTag wrapped in quotes and while exec the docker run comand there is an error of invalid reference format for docker.
maybe this problem is only on windows machines

```suggestion
const dockerTag = argv.filter((x) => x.startsWith('--containerTag='))[0]?.split('=')[1].replace(/['"]+/g, '')
```

2023-07-26 13:54 UTC, vlad-dubrovski commented on acceptance-test/docker.test.ts
> +const dockerTag = argv.filter((x) => x.startsWith('--containerTag='))[0]?.split('=')[1]
@iryna-markovich-vocovo yep, on MAC is fine. I will correct it.

2023-07-27 10:09 UTC, vlad-dubrovski commented on .nvmrc
> +v16.13.2
@iryna-markovich-vocovo https://nodejs.org/en 18.17.0

2023-07-27 11:58 UTC, closed without merging